app/models/chat.py
from sqlalchemy import func

from app import db
from app.models.base import Base


class Chat(Base):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(300))
    about = db.Column(db.String(4000))

    creator_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    posts = db.relationship('Post', backref='chat', lazy='dynamic')

    def __repr__(self):
        return '<Chat {}>'.format(self.name)

    # Custom queries

    @staticmethod
    def get_by_name(name):
        return Chat.query.filter(func.lower(Chat.name) == func.lower(name)).first()

app/blueprints/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, FileField, SelectField
from wtforms.validators import DataRequired
from flask_wtf.file import FileAllowed

from app import db, images
from app.models import Chat, User, Post, Comment
from app.util.validators import ValidName, Unique, ValidLength


class NewPostForm(FlaskForm):
    chat_name = SelectField('Chat', validators=[DataRequired('Please select a chat')])
    title = StringField('Title', validators=[DataRequired(), ValidLength(Post.title)])
    body = TextAreaField('Text area', validators=[ValidLength(Post.body)])
    image = FileField('Image', validators=[FileAllowed(images, 'Image Only!')])
    submit = SubmitField('Submit')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.chat_name.choices = [(0, '-----')] + [(chat.name, chat.name) for chat in Chat.query.all()]


class NewChatForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), ValidLength(Chat.name), ValidName(),
                                           Unique(Chat.get_by_name, 'That chat name is already taken.')])
    about = TextAreaField('Description', validators=[DataRequired(), ValidLength(Chat.about)])
    submit = SubmitField('Submit')


class NewCommentForm(FlaskForm):
    body = TextAreaField('Comment', validators=[DataRequired(), ValidLength(Comment.body)])
    submit = SubmitField('Submit')


class SearchForm(FlaskForm):
    search = StringField('Search')


class EditProfileForm(FlaskForm):
    about_me = TextAreaField('About me',
                             validators=[ValidLength(User.about_me)])
    submit = SubmitField('Submit')


class EditChatForm(FlaskForm):
    about = TextAreaField('Description', validators=[ValidLength(Chat.about)])
    submit = SubmitField('Submit')

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.blueprints.main import routes

app/blueprints/main/routes/__init__.py
from datetime import datetime
from flask import render_template, flash, redirect, request, url_for, current_app, abort
from flask_login import current_user, login_required
import sqlalchemy as sa
from sqlalchemy import func

from app.blueprints.main import bp
from app import db
from app.models import User, Post, Vote, Image, Chat, Sub, Comment
from app.blueprints.main.forms import SearchForm


def paginate(items, per_page=None):
    if per_page is None:
        per_page = current_app.config['DEFAULT_PER_PAGE']

    page = request.args.get('page', 1, type=int)
    items = items.paginate(page, per_page, False)

    next_url = url_for(request.endpoint, page=items.next_num) if items.has_next else None
    prev_url = url_for(request.endpoint, page=items.prev_num) if items.has_prev else None
    return items, next_url, prev_url


@bp.before_app_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()


# ------------------------------ FRONT PAGES ------------------------------

@bp.route('/')
@bp.route('/index')
def index():
    return render_template('main/home.html', title='Home')


@bp.route('/feed')
@login_required
def feed():
    posts = current_user.subscribed_posts().order_by(Post.created_at.desc())

    posts, next_url, prev_url = paginate(posts, current_app.config['POSTS_PER_PAGE'])

    return render_template('main/feed.html', title='Your Feed', posts=posts.items, next_url=next_url, prev_url=prev_url)


@bp.route('/popular', methods=['GET', 'POST'])
def popular():
    search_form = SearchForm()
    posts = db.session.query(Post)

    if search_form.validate_on_submit():
        posts = posts.filter(Post.title.like('%' + search_form.search.data + '%') |
                             Post.body.like('%' + search_form.search.data + '%'))

    posts = posts.order_by(sa.desc(Post.score))
    posts, next_url, prev_url = paginate(posts, current_app.config['POSTS_PER_PAGE'])

    return render_template('main/popular.html', title='Popular',
                           posts=posts.items, next_url=next_url, prev_url=prev_url,
                           form=search_form, include_chat=True)


@bp.route('/explore_chats', methods=['GET', 'POST'])
def explore_chats():
    form = SearchForm()
    chats = db.session.query(Chat)

    if form.validate_on_submit():
        chats = chats.filter(Chat.name.like('%' + form.search.data + '%') |
                             Chat.about.like('%' + form.search.data + '%'))

    chats = chats.outerjoin(Sub).group_by(Chat.id).order_by(func.count().desc())
    chats, next_url, prev_url = paginate(chats, current_app.config['CHATS_PER_PAGE'])

    return render_template('main/explore_chats.html', title='Explore',
                           chats=chats.items, next_url=next_url, prev_url=prev_url,
                           form=form)


@bp.route('/leaderboard', methods=['GET', 'POST'])
def leaderboard():
    search_form = SearchForm()
    users = db.session.query(User)

    if search_form.validate_on_submit():
        users = users.filter(User.username.like('%' + search_form.search.data + '%'))

    users = users.order_by(sa.desc(User.score))
    users, next_url, prev_url = paginate(users, current_app.config['USERS_PER_PAGE'])

    return render_template('main/leaderboard.html', title='Leaderboard',
                           users=users.items, next_url=next_url, prev_url=prev_url,
                           form=search_form)


# ------------------------------ FUNCTIONAL PAGES ------------------------------

from .users import *
from .chats import *
from .posts import *
from .votes import *

app/blueprints/main/routes/chats.py
from flask import render_template, flash, redirect, request, url_for, current_app, abort
from flask_login import current_user, login_required

from app.blueprints.main import bp
from app import db
from app.models import Post, Chat
from app.blueprints.main.forms import NewChatForm, EditChatForm

from . import paginate


# ------------------------------ CHATS ------------------------------

@bp.route('/chat/<name>', methods=['GET', 'POST'])
def show_chat(name):
    chat = Chat.get_by_name(name)
    if chat is None:
        return abort(404)

    posts = Post.query.filter_by(chat=chat).order_by(Post.created_at.desc())
    posts, next_url, prev_url = paginate(posts, current_app.config['POSTS_PER_PAGE'])

    return render_template('main/chat.html', title=chat.name, chat=chat,
                           posts=posts.items, next_url=next_url, prev_url=prev_url)


@bp.route('/create_chat', methods=['GET', 'POST'])
@login_required
def create_chat():
    form = NewChatForm()

    if form.validate_on_submit():
        new_chat = Chat(name=form.name.data, about=form.about.data, creator=current_user)
        current_user.subscribe(new_chat)
        db.session.add(new_chat)
        db.session.commit()
        flash('Your new chat is now live!')
        return redirect(url_for('main.show_chat', name=new_chat.name))

    return render_template('main/create_chat.html', title="New Chat", form=form)


@bp.route('/edit_chat/<name>', methods=['GET', 'POST'])
@login_required
def edit_chat(name):
    chat = Chat.get_by_name(name)
    if chat is None:
        return abort(404)
    if chat not in current_user.chats:
        flash('You cannot edit this chat.')
        return redirect(url_for('show_chat', name=name))
    form = EditChatForm()
    if form.validate_on_submit():
        chat.about = form.about.data
        db.session.commit()
        flash('Your changes have been saved.')
        return redirect(url_for('main.show_chat', name=chat.name))
    elif request.method == 'GET':
        form.about.data = chat.about
    return render_template('main/edit_chat.html', title='Edit chat/{}'.format(chat.name), chat=chat,
                           form=form)


# ------------------------------ SUBSCRIBING ------------------------------

def set_subscribed(name, sub):
    chat = Chat.get_by_name(name)
    if chat is None:
        return None
    current_user.set_subscribed(chat, sub)
    db.session.commit()
    return chat


@bp.route('/subscribe/<name>')
@login_required
def subscribe(name):
    found = set_subscribed(name, True)
    if found is None:
        flash('Chat {} not found.'.format(name))
        return redirect(url_for('main.index'))
    flash('You subscribed to chat/{}!'.format(name))
    return redirect(request.referrer or url_for('main.show_chat', name=name))


@bp.route('/unsubscribe/<name>')
@login_required
def unsubscribe(name):
    found = set_subscribed(name, False)
    if found is None:
        flash('Chat {} not found.'.format(name))
        return redirect(url_for('main.index'))
    flash('You unsubscribed from chat/{}!'.format(name))
    return redirect(request.referrer or url_for('main.show_chat', name=name))

app/blueprints/main/routes/posts.py
from flask import render_template, flash, redirect, request, url_for, current_app, abort
from flask_login import current_user, login_required

from app.blueprints.main import bp
from app import db, images
from app.models import Post, Image, Chat, Comment
from app.blueprints.main.forms import NewPostForm, NewCommentForm

from . import paginate


# ------------------------------ POSTS ------------------------------

@bp.route('/post/<post_id>', methods=['GET', 'POST'])
def show_post(post_id):
    post = Post.query.filter_by(id=post_id).first_or_404()

    form = NewCommentForm()
    if form.validate_on_submit():
        comment = Comment(body=form.body.data,
                          author=None if current_user.is_anonymous else current_user)
        comment.post = post
        db.session.add(comment)
        db.session.commit()
        flash('Your comment is now live!')
        return redirect(url_for('main.show_post', post_id=post_id))

    comments = Comment.query.filter_by(post_id=post_id).order_by(Comment.created_at.desc())
    comments, next_url, prev_url = paginate(comments, current_app.config['COMMENTS_PER_PAGE'])

    return render_template('main/post.html', title=post.title, post=post,
                           comments=comments.items, next_url=next_url, prev_url=prev_url,
                           form=form)


@bp.route('/make_post', methods=['GET', 'POST'], defaults={'chat_name': None})
@bp.route('/make_post/<chat_name>', methods=['GET', 'POST'])
@login_required
def make_post(chat_name):
    form = NewPostForm(chat_name=chat_name)
    if form.validate_on_submit():
        chat_name = form.chat_name.data

        new_post = Post(title=form.title.data, body=form.body.data, author=current_user)
        new_post.chat = Chat.query.filter_by(name=chat_name).first()

        if 'image' in request.files and request.files['image']:
            filename = images.save(form.image.data)
            url = images.url(filename)
            image = Image(filename=filename, url=url)
            new_post.attachment = image

        db.session.add(new_post)
        db.session.commit()
        flash('Your new post is now live!')
        return redirect(url_for('main.show_chat', name=chat_name))
    return render_template('main/make_post.html', title="New Post", form=form)


@bp.route('/delete_post/<post_id>', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.filter_by(id=post_id).first()
    if post is None:
        flash('The post you are trying to delete does not exist.')
        return redirect(request.referrer or url_for('main.index'))
    chat_name = post.chat.name

    db.session.delete(post)
    db.session.commit()
    flash('You deleted the post.')
    return redirect(request.referrer or url_for('main.show_chat', name=chat_name))

app/blueprints/main/routes/users.py
from flask import render_template, flash, redirect, request, url_for, current_app, abort
from flask_login import current_user, login_required

from app.blueprints.main import bp
from app import db, images
from app.models import User, Post
from app.blueprints.main.forms import EditProfileForm

from . import paginate


# ------------------------------ USERS ------------------------------

@bp.route('/user/<username>')
def show_user(username):
    user = User.get_by_username(username)
    if user is None:
        return abort(404)

    posts = Post.query.filter_by(author=user).order_by(Post.created_at.desc())
    posts, next_url, prev_url = paginate(posts, current_app.config['POSTS_PER_PAGE'])

    return render_template('main/user.html', user=user,
                           posts=posts.items, next_url=next_url, prev_url=prev_url,
                           include_chat=True)


@bp.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.about_me = form.about_me.data
        db.session.commit()
        flash('Your changes have been saved.')
        return redirect(url_for('main.show_user', username=current_user.username))
    elif request.method == 'GET':
        form.about_me.data = current_user.about_me
    return render_template('main/edit_profile.html', title='Edit Profile',
                           form=form)

app/blueprints/main/routes/votes.py
from flask import render_template, flash, redirect, request, url_for, current_app, abort
from flask_login import current_user, login_required

from app.blueprints.main import bp
from app import db
from app.models import Post, Comment


# ------------------------------ VOTES ------------------------------

def vote_post(post_id, liked):
    """ Vote on a post """
    post = Post.query.filter_by(id=post_id).first()
    if post is None:
        return None
    vote = current_user.vote(post, liked)
    db.session.merge(vote)
    db.session.commit()
    return post


def vote_comment(comment_id, liked):
    """ Vote on a comment """
    comment = Comment.query.filter_by(id=comment_id).first()
    if comment is None:
        return None
    vote = current_user.vote(comment, liked)
    db.session.merge(vote)
    db.session.commit()
    return comment


@bp.route('/upvote/<post_id>')
@login_required
def upvote(post_id):
    """ Page to upvote a post """
    found = vote_post(post_id, True)
    if found is None:
        flash('Post not found.')
        return redirect(url_for('main.index'))
    flash('You upvoted the post!')
    return redirect(request.referrer or url_for('main.show_post', post_id=post_id))


@bp.route('/downvote/<post_id>')
@login_required
def downvote(post_id):
    """ Page to downvote a post """
    found = vote_post(post_id, False)
    if found is None:
        flash('Post not found.')
        return redirect(url_for('main.index'))
    flash('You downvoted the post!')
    return redirect(request.referrer or url_for('main.show_post', post_id=post_id))


@bp.route('/upvote_comment/<comment_id>')
@login_required
def upvote_comment(comment_id):
    """ Page to upvote a comment """
    found = vote_comment(comment_id, True)
    if found is None:
        flash('Comment not found.')
        return redirect(url_for('main.index'))
    flash('You voted on the comment!')
    return redirect(request.referrer or url_for('main.show_post', post_id=found.post_id, comment_id=comment_id))


@bp.route('/downvote_comment/<comment_id>')
@login_required
def downvote_comment(comment_id):
    """ Page to downvote a comment """
    found = vote_comment(comment_id, False)
    if found is None:
        flash('Comment not found.')
        return redirect(url_for('main.index'))
    flash('You voted on the comment!')
    return redirect(request.referrer or url_for('main.show_post', post_id=found.post_id, comment_id=comment_id))


# ------------------------------ WITHDRAW VOTES ------------------------------

def withdraw_vote_post(post_id):
    """ Withdraw vote from a post """
    post = Post.query.filter_by(id=post_id).first()
    if post is None:
        return None
    current_user.withdraw_vote(post)
    db.session.commit()
    return post


def withdraw_vote_comm(comment_id):
    """ Withdraw vote from a comment """
    comment = Comment.query.filter_by(id=comment_id).first()
    if comment is None:
        return None
    current_user.withdraw_vote(comment)
    db.session.commit()
    return comment


@bp.route('/withdraw_vote/<post_id>')
@login_required
def withdraw_vote(post_id):
    """ Page to withdraw your vote from a post """
    found = withdraw_vote_post(post_id)
    if found is None:
        flash('Post not found.')
        return redirect(url_for('main.index'))
    flash('You withdrew your vote.')
    return redirect(request.referrer or url_for('main.show_post', post_id=post_id))


@bp.route('/withdraw_vote_comment/<comment_id>')
@login_required
def withdraw_vote_comment(comment_id):
    """ Page to withdraw your vote from a comment """
    found = withdraw_vote_comm(comment_id)
    if found is None:
        flash('Comment not found.')
        return redirect(url_for('main.index'))
    flash('You withdrew your vote.')
    return redirect(request.referrer or url_for('main.show_post', post_id=found.post_id, comment_id=comment_id))

app/templates/main/_commentvote.html
{% if current_user.is_anonymous %}
{% else %}
    {% set vote = current_user.already_voted(comment) %}

    {% if vote and vote.liked %}
        <a class="vote-button upvote selected" href="{{ url_for('main.withdraw_vote_comment', comment_id=comment.id) }}">
            <i class="glyphicon glyphicon-arrow-up"></i>
        </a>
    {% else %}
        <a class="vote-button upvote" href="{{ url_for('main.upvote_comment', comment_id=comment.id) }}">
            <i class="glyphicon glyphicon-arrow-up"></i>
        </a>
    {% endif %}

    {% if vote and not vote.liked %}
        <a class="vote-button downvote selected" href="{{ url_for('main.withdraw_vote_comment', comment_id=comment.id) }}">
            <i class="glyphicon glyphicon-arrow-down"></i>
        </a>
    {% else %}
        <a class="vote-button downvote" href="{{ url_for('main.downvote_comment', comment_id=comment.id) }}">
            <i class="glyphicon glyphicon-arrow-down"></i>
        </a>
    {% endif %}
{% endif %}

app/templates/main/_subscribe.html
{% if current_user.is_anonymous %}
{% else %}
    {% if not current_user.is_subscribed(chat) %}
        <a class="like-button" href="{{ url_for('main.subscribe', name=chat.name) }}">Subscribe</a>
    {% else %}
        <a class="unlike-button" href="{{ url_for('main.unsubscribe', name=chat.name) }}">Subscribed</a>
    {% endif %}
{% endif %}

app/templates/main/_user.html
    <table class="table table-hover">
        <tr>
            <td width="50px">
                <a href="{{ url_for('main.show_user', username=user.username) }}">
                    <img alt src="{{ user.avatar(50) }}" />
                </a>
            </td>
            <td width="100%">
                <a href="{{ url_for('main.show_user', username=user.username) }}">
                    {{ user.username }}
                </a>
            </td>
            <td>
                Score: {{ user.score }}
            </td>
        </tr>
    </table>

app/templates/main/_vote.html
{% if current_user.is_anonymous %}
{% else %}
    {% set vote = current_user.already_voted(post) %}

    {% if vote and vote.liked %}
        <a class="vote-button upvote selected" href="{{ url_for('main.withdraw_vote', post_id=post.id) }}">
            <i class="glyphicon glyphicon-arrow-up"></i>
        </a>
    {% else %}
        <a class="vote-button upvote" href="{{ url_for('main.upvote', post_id=post.id) }}">
            <i class="glyphicon glyphicon-arrow-up"></i>
        </a>
    {% endif %}

    {% if vote and not vote.liked %}
        <a class="vote-button downvote selected" href="{{ url_for('main.withdraw_vote', post_id=post.id) }}">
            <i class="glyphicon glyphicon-arrow-down"></i>
        </a>
    {% else %}
        <a class="vote-button downvote" href="{{ url_for('main.downvote', post_id=post.id) }}">
            <i class="glyphicon glyphicon-arrow-down"></i>
        </a>
    {% endif %}

{% endif %}

app/templates/main/chat.html
{% extends "main/layout.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    {% include "main/_subscribe.html" %}

    <h1>chat/{{ chat.name }}</h1>
    <p>
        {{ chat.about }}
        {% if current_user == chat.creator %}
            <a href="{{ url_for('main.edit_chat', name=chat.name) }}">Edit</a>
        {% endif %}
    </p>
    <p>{{ chat.subscribers.count() }} subscribers</p>

    <br><br>
    <a href="{{ url_for('main.make_post', chat_name=chat.name) }}">Make a Post</a>
    <br><br>
    {% for post in posts %}
        {% include 'main/_post.html' %}
    {% endfor %}
    {% include '_pager.html' %}
{% endblock %}

app/templates/main/edit.html
{% extends "main/layout.html" %}

{% block app_content %}
    <h1>Edit</h1>
    <form action="" method="post">
        {{ form.email }}
        {{ form.password }}
        {{ form.csrf_token }}
    </form>
{% endblock %}

app/templates/main/edit_chat.html
{% extends "main/layout.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Edit chat/{{ chat.name }}</h1>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/main/explore_chats.html
{% extends "main/layout.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h3>Hi, {{ current_user.username or "Anonymous" }}!</h3>
    <h1>Top Chats</h1>
    <a href="{{ url_for('main.create_chat') }}">Create a new chat</a>
    <br><br>

    {% if chats %}
        {{ wtf.quick_form(form) }}
        {% for chat in chats %}
            {% include 'main/_chat.html' %}
        {% endfor %}
        {% include '_pager.html' %}
    {% else %}
        <p>No results.</p>
    {% endif %}
{% endblock %}

app/templates/main/feed.html
{% extends "main/layout.html" %}

{% block app_content %}
    <h3>Hi, {{ current_user.username }}!</h3>
    <h1>Your Feed</h1>

    {% if posts %}
        {% for post in posts %}
            {% include 'main/_post.html' %}
        {% endfor %}
        {% include '_pager.html' %}
    {% else %}
        <p>Nothing here. <a href="{{ url_for('main.explore_chats') }}">Find some chats to follow.</a></p>
    {% endif %}
{% endblock %}

app/templates/main/layout.html
{% extends "layout.html" %}

{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
{% endblock %}

app/templates/main/make_post.html
{% extends "main/layout.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <div class="container">
        {{ wtf.quick_form(form) }}
    </div>
{% endblock %}

app/templates/main/popular.html
{% extends "main/layout.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h3>Hi, {{ current_user.username or "Anonymous" }}!</h3>
    <h1>Popular</h1>

    {% if posts %}
        {{ wtf.quick_form(form) }}
        {% for post in posts %}
            {% include 'main/_post.html' %}
        {% endfor %}
        {% include '_pager.html' %}
    {% else %}
        <p>No results.</p>
    {% endif %}
{% endblock %}

app/templates/main/post.html
{% extends "main/layout.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}

    <a class='nounderline' href="{{ url_for('main.show_user', username=post.author.username) }}">
        <img alt src="{{ post.author.avatar(25) }}" />
    </a>
    <a href="{{ url_for('main.show_user', username=post.author.username) }}">
        {{ post.author.username }}
    </a>
    in <a href="{{ url_for('main.show_chat', name=post.chat.name) }}">chat/{{ post.chat.name }}</a>
    posted {{ moment(post.created_at).fromNow() }}:

    <br><br>
    <table>
        <tr>
            <td width="20px">
                {{ post.score }}
            </td>
            <td>
                {% include "main/_vote.html" %}
            </td>
        </tr>
    </table>

    <h2>{{ post.title }}</h2>
    {% if post.attachment %}
        <img class="attachment-big" alt="{{ post.attachment.filename }}" src="{{ post.attachment.url }}">
        <br><br>
    {% endif %}
    <p>{{ post.body_e|safe }}</p>

    <br>
    <div class="container">
        {{ wtf.quick_form(form) }}
    </div>
    <br>
    {% for comment in comments %}
        {% include 'main/_comment.html' %}
    {% endfor %}
    {% include '_pager.html' %}
{% endblock %}

app/templates/main/user.html
{% extends "main/layout.html" %}

{% block app_content %}
    <table class="table table-hover">
        <tr>
            <td width="128px"><img alt src="{{ user.avatar(128) }}"></td>
            <td>
                <h1>u/{{ user.username }}</h1>
                {% if user.about_me %}<p>{{ user.about_me_|safe }}</p>{% endif %}
                <p>User score: {{ user.score }}</p>
                {% if user.last_seen %}
                    <p>Last seen on: {{ moment(user.last_seen).format('LLL') }}</p>
                {% endif %}
                {% if user == current_user %}
                    <p><a href="{{ url_for('main.edit_profile') }}">Edit your profile</a></p>
                {% endif %}
            </td>
        </tr>
    </table>
    <h2>Posts</h2>
    {% for post in posts %}
        {% include 'main/_post.html' %}
    {% endfor %}
    {% include '_pager.html' %}
{% endblock %}